### ISSUE TITLE
Make editor panel resizable

### ISSUE THREAD

**Issue by bogdan-stefan-hs** [skidding/react-cosmos#193]
## Need
```gherkin
As a user
I want to be able to resize the editor panel
So that I can use the screen space efficiently.
```
## Deliverables
- [ ] The separator between the editor and preview panes can be dragged to resize them (when the editor pane enlarges, the preview pane shrinks and vice versa)

#### Prerequisites
- Use the React SplitPane component located [here](https://github.com/ubervu/react-split-pane)

#### TODO
- [ ] Add the editor and preview pane components to a SplitPane 
- [ ] Adapt old tests and add new ones

**Comment by bogdan-stefan-hs** [comment]
@skidding I already wrote the code for this, but I have a few questions to ask/debate:

1. I forked the original `react-split-pane` package/repo and republished it to add custom classname support. This is because CP adds a hash to classes in the `less-loader`, to avoid conflicts with possible components, so styling is impossible on classes that don't abide to that rule.

However, as I developed further and needed another package, the problem reappeared and I realized republishing packages is not a feasible solution.

So the solution I came up with was: add a new less loader for everything that is not a playground internal, and exclude from it everything loaded by the first loader.

WIth this solution we can use either of `react-split-pane` and `ubervu-react-split-pane`, BUT a conflict can arise if someone loads a component with the exact classnames of the split pane DOM elements.

2. Another problem that will arise now, with multiple React version support, is that these new packages will probably not work with any version. `react-dom-polyfill` won't be good either, since they use `getDomNode()` instead of `findDomNode()`.

So the only solution I can think of is to install a different version of the package on `npm install-react:vXX`. This only leaves us with using the original `react-split-pane`, since it has multiple releases.

WDYT?

**Comment by skidding** [comment]
> I forked the original react-split-pane package/repo and republished it to add custom classname support. This is because CP adds a hash to classes in the less-loader, to avoid conflicts with possible components, so styling is impossible on classes that don't abide to that rule.

This shouldn't be a problem anymore, since [the LESS loader in the new webpack config only targets the react-component-playground/src folder](https://github.com/skidding/react-cosmos/blob/e6f100806ab3c9dcc6e3dad4704cc92ea87cf3f3/packages/react-component-playground/webpack.config.js#L37-L40).

> Another problem that will arise now, with multiple React version support, is that these new packages will probably not work with any version. react-dom-polyfill won't be good either, since they use getDomNode() instead of findDomNode().

I see the following options:

1. Avoid using 3rd party React components in CP. Sounds harsh, but after all CP is designed to be a thin, lightweight wrapper that loads components from the user land. Not saying avoid 3rd party libs, just stuff that uses ReactDOM or new features of React. (Not sure what the complexity of `react-split-pane is`, so this might not be feasible in this case)
2. Use a fork of 3rd party React component where you replace ReactDOM with react-dom-polyfill
3. Submit a PR to 3rd party React component repo replacing ReactDOM with react-dom-polyfill, maybe they welcome it. After all, it makes their lib available for more React versions.

> So the only solution I can think of is to install a different version of the package on `npm install-react:vXX`. This only leaves us with using the original react-split-pane, since it has multiple releases.

This doesn't sound like a solution to me. `npm install-react:vXX` is a dev command. The published libs will be the same for everyone, so they can't work for any user React version if not all dependencies do as well. Am I missing something?

**Comment by bogdan-stefan-hs** [comment]
> CP is designed to be a thin, lightweight wrapper that loads components from the user land

I agree with and respect that. `react-split-pane` is pretty light though, it seems ok to use it.

> Use a fork of 3rd party React component where you replace ReactDOM with react-dom-polyfill

I will do this for now, since i already published a fork and only need to update it and release a new version. In the future I'll try and avoid these React libs.

Sorry if any of my comments are inappropriate, i'm still new to React and npm land. :blush:

**Comment by skidding** [comment]
Sounds good. If you start from the latest master and only integrate
react-dom-polyfill it's worth creating a PR on the original split pane
project as well after this is done.

Your comments are very thoughtful! And publishing React components through
npm has always been tricky.
